matrix:
  allow_failures:
    - os: windows
    - os: osx
  include:
    - os: osx
      before_install:
        - curl -s http://get.sdkman.io | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install java 8.0.202-zulu
        - sudo safaridriver --enable
      script: ./gradlew clean test -Dbrowser=safari
    - os: linux
      language: java
      jdk: openjdk8
      script: ./gradlew clean test -Dbrowser=firefox-headless
#    - os: windows
#      language: shell
#      before_install:
#        - source .travis/windows/prepare.sh
#        - bash .travis/windows/java.sh
#      script: gradlew.bat clean test -Dbrowser=ie

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
